### ISSUE TITLE
Missing break in stm32u0xx_ll_rcc.c LL_RCC_GetADCClockFreq() case LL_RCC_ADC_CLKSOURCE_PLLP

### ISSUE THREAD

**Issue by CanastraRF** [STMicroelectronics/STM32CubeU0#1]
Hi
my compiler report a missing break in Funktion LL_RCC_GetADCClockFreq() for case LL_RCC_ADC_CLKSOURCE_PLLP:
Please fix this
Please enable most warning in your tool chain. Modern tools report this.

**Comment by RJMSTM** [comment]
ST Internal Reference: 181766

**Comment by TOUNSTM** [comment]
Fixed in 6452b2170313f522b4a3372054d2462b77d890d1
