### ISSUE TITLE
unreachable code in stm32u0xx_hal_lptim.c 

### ISSUE THREAD

**Issue by CanastraRF** [STMicroelectronics/STM32CubeU0#2]
In stm32u0xx_hal_lptim.c are two lines where my compiler reports unreachable code.

Function HAL_LPTIM_IC_Stop_IT()
default:
return HAL_ERROR;
break;

Function HAL_LPTIM_IC_Stop_DMA()
default:
return HAL_ERROR;
break;

Please remove the unnecessary break;

**Comment by RJMSTM** [comment]
ST Internal Reference: 182062
