### ISSUE TITLE
stm32u0xx_hal_rtc_ex.h: #define RTC_BKP_NB inconssitency to DS14581 - Rev 2

### ISSUE THREAD

**Issue by ChristianGrau5452** [STMicroelectronics/STM32CubeU0#4]
Dear all

The datasheet DS14581 - Rev 2 in chapter "Real-time clock (RTC), tamper (TAMP) and backup registers" states that the RTC has 20 bytes of user application data.

This seems inconsissten to the cube code in stm32u0xx_hal_rtc_ex.h: where #define RTC_BKP_NB is 9U.

What is correct?

Thank you for the clarification and kind regards

Christian

**Comment by ALABSTM** [comment]
Hi @ChristianGrau5452,

In DS14581 you referenced, but also in DS14548, it is clearly written:
* "with RTC and **9** x 32-bit backup registers", at page 1, in the "Features" section,
* "The device embeds an RTC and **nine** 32-bit backup registers", in the paragraph you mentioned.

Hence, there is **no inconsistency** from the driver's side. However, I agree this mention of "keeping **20** bytes of user application data" is quite puzzling.

I'll dig deeper and let you know once I have something.

With regards,

**Comment by ALABSTM** [comment]
ST Internal Reference: 184761

**Comment by ALABSTM** [comment]
Hi @ChristianGrau5452,

Looks like you are right and your point is valid. My apologies. There is indeed a discrepancy. The fix is likely to impact both the datasheet and the firmware. To be continued...

With regards,

**Comment by ALABSTM** [comment]
Hi @ChristianGrau5452,

New turnaround. The hardware design team confirms all STM32U0xx lines have the **same number** of backup registers, which is **9**.

 Hence, the defect is in the documentation, **i.e.**, the datasheets. The sentence "The backup registers allow keeping **20** bytes" shall be changed into "The backup registers allow keeping **36** bytes".

Thank you very much for having posted this question as it helped us to spot this defect in the documentation. New versions of the datasheets shall be available soon hopefully. I cannot share a date for the moment.

As there is no impact on the firmware published within this repository, please allow me to close this issue. Thank you for your comprehension.

With regards,
