### ISSUE TITLE
Duplicate file?

### ISSUE THREAD

**Issue by fpistm** [STMicroelectronics/STM32CubeU0#6]
Hi
I think this file should not be here:
https://github.com/STMicroelectronics/cmsis_device_u0/blob/main/Source/Templates/gcc/startup_stm32u0xx.s

It seems a duplicate of https://github.com/STMicroelectronics/cmsis_device_u0/blob/main/Source/Templates/gcc/startup_stm32u083xx.s

**Comment by ALABSTM** [comment]
Hi @fpistm,

Looks like you're right. Thank you for the heads-up. We'll forward your report to our development teams to ask for their confirmation prior to any further action. We'll keep you informed.

With regards,

**Comment by TOUNSTM** [comment]
ST Internal Reference: 189304

**Comment by TOUNSTM** [comment]
Fixed in 0d4244dc877a194c567fc29107b63023a1efb4bb
